# Generated by Django 3.1.4 on 2021-04-21 07:38

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('shop_type', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('profile_photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('profile_photo_crop', image_cropping.fields.ImageRatioField('profile_photo', '270x303', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='profile photo crop')),
                ('feature_photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('feature_photo_crop', image_cropping.fields.ImageRatioField('feature_photo', '470x620', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='feature photo crop')),
                ('slider_photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('slider_photo_crop', image_cropping.fields.ImageRatioField('slider_photo', '1030x550', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='slider photo crop')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
                ('photo_1_crop', image_cropping.fields.ImageRatioField('photo_1', '330x250', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='photo 1 crop')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
                ('photo_2_crop', image_cropping.fields.ImageRatioField('photo_2', '330x250', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='photo 2 crop')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
                ('photo_3_crop', image_cropping.fields.ImageRatioField('photo_3', '330x250', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='photo 3 crop')),
                ('description_1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=200)),
                ('facebook', models.CharField(blank=True, max_length=200)),
                ('twitter', models.CharField(blank=True, max_length=200)),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('youtube', models.CharField(blank=True, max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('owner_view', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('product_type', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('is_mvp', models.BooleanField(default=True)),
                ('profile_photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('profile_photo_crop', image_cropping.fields.ImageRatioField('profile_photo', '270x303', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='profile photo crop')),
                ('original_rate', models.IntegerField(blank=0)),
                ('discounted_rate', models.IntegerField(blank=0)),
                ('description_1', ckeditor.fields.RichTextField()),
                ('is_size', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('tag', models.CharField(blank=True, max_length=200)),
                ('photo_1', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_1_crop', image_cropping.fields.ImageRatioField('photo_1', '440x520', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='photo 1 crop')),
                ('photo_2', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_2_crop', image_cropping.fields.ImageRatioField('photo_2', '440x520', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='photo 2 crop')),
                ('photo_3', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_3_crop', image_cropping.fields.ImageRatioField('photo_3', '440x520', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='photo 3 crop')),
                ('description_main', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('description_image_crop', image_cropping.fields.ImageRatioField('description_image', '369x460', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='description image crop')),
                ('stock_available', models.CharField(blank=True, max_length=200)),
                ('weight', models.CharField(blank=True, max_length=200)),
                ('size', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(blank=True, max_length=200)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
    ]
