# Generated by Django 3.1.4 on 2021-04-21 07:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210421_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_main',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_available',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description_1',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='tag',
            field=models.CharField(max_length=200),
        ),
    ]
