# Generated by Django 3.1.4 on 2021-04-21 11:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210421_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('approved_by', models.CharField(max_length=200)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
    ]
