# Generated by Django 3.1.4 on 2021-04-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
